# permissions for end users to view domains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailcow-operator
    app.kubernetes.io/managed-by: kustomize
  name: domain-viewer-role
rules:
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - domains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - domains/status
  verbs:
  - get
