# permissions for end users to view domainadmins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailcow-operator
    app.kubernetes.io/managed-by: kustomize
  name: domainadmin-viewer-role
rules:
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - domainadmins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - domainadmins/status
  verbs:
  - get
