# permissions for end users to edit mailboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailcow-operator
    app.kubernetes.io/managed-by: kustomize
  name: mailbox-editor-role
rules:
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - mailboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - mailboxes/status
  verbs:
  - get
