apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - aliases
  - domainadmins
  - domains
  - mailboxes
  - mailcows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - aliases/finalizers
  - domainadmins/finalizers
  - domains/finalizers
  - mailboxes/finalizers
  - mailcows/finalizers
  verbs:
  - update
- apiGroups:
  - mailcow.onestein.nl
  resources:
  - aliases/status
  - domainadmins/status
  - domains/status
  - mailboxes/status
  - mailcows/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
